Status(contributors = None, truncated = False, text = u 'VAI PORRA  #worldcup', in_reply_to_status_id = None, id = 481147532840824833, favorite_count = 0, _api = < tweepy.api.API object at 0x109078e90 > , author = User(follow_request_sent = None, profile_use_background_image = True, _json = {
    u 'follow_request_sent': None,
    u 'profile_use_background_image': True,
    u 'default_profile_image': False,
    u 'id': 928197300,
    u 'verified': False,
    u 'profile_image_url_https': u 'https://pbs.twimg.com/profile_images/478566662136803330/En6dtdRp_normal.jpeg',
    u 'profile_sidebar_fill_color': u 'DDEEF6',
    u 'profile_text_color': u '333333',
    u 'followers_count': 205,
    u 'profile_sidebar_border_color': u 'FFFFFF',
    u 'id_str': u '928197300',
    u 'profile_background_color': u 'C0DEED',
    u 'listed_count': 0,
    u 'profile_background_image_url_https': u 'https://pbs.twimg.com/profile_background_images/479444187616518144/TbB97uZ7.jpeg',
    u 'utc_offset': None,
    u 'statuses_count': 584,
    u 'description': u 'Talking Winning',
    u 'friends_count': 915,
    u 'location': u 'swangg',
    u 'profile_link_color': u '0084B4',
    u 'profile_image_url': u 'http://pbs.twimg.com/profile_images/478566662136803330/En6dtdRp_normal.jpeg',
    u 'following': None,
    u 'geo_enabled': True,
    u 'profile_banner_url': u 'https://pbs.twimg.com/profile_banners/928197300/1403143442',
    u 'profile_background_image_url': u 'http://pbs.twimg.com/profile_background_images/479444187616518144/TbB97uZ7.jpeg',
    u 'name': u 'mc bacelar',
    u 'lang': u 'pt',
    u 'profile_background_tile': True,
    u 'favourites_count': 10,
    u 'screen_name': u 'bacelar_santos',
    u 'notifications': None,
    u 'url': None,
    u 'created_at': u 'Mon Nov 05 18:59:10 +0000 2012',
    u 'contributors_enabled': False,
    u 'time_zone': None,
    u 'protected': False,
    u 'default_profile': False,
    u 'is_translator': False
}, id = 928197300, _api = < tweepy.api.API object at 0x109078e90 > , verified = False, profile_image_url_https = u 'https://pbs.twimg.com/profile_images/478566662136803330/En6dtdRp_normal.jpeg', profile_sidebar_fill_color = u 'DDEEF6', is_translator = False, geo_enabled = True, profile_text_color = u '333333', followers_count = 205, protected = False, location = u 'swangg', default_profile_image = False, id_str = u '928197300', utc_offset = None, statuses_count = 584, description = u 'Talking Winning', friends_count = 915, profile_link_color = u '0084B4', profile_image_url = u 'http://pbs.twimg.com/profile_images/478566662136803330/En6dtdRp_normal.jpeg', notifications = None, profile_background_image_url_https = u 'https://pbs.twimg.com/profile_background_images/479444187616518144/TbB97uZ7.jpeg', profile_background_color = u 'C0DEED', profile_banner_url = u 'https://pbs.twimg.com/profile_banners/928197300/1403143442', profile_background_image_url = u 'http://pbs.twimg.com/profile_background_images/479444187616518144/TbB97uZ7.jpeg', screen_name = u 'bacelar_santos', lang = u 'pt', profile_background_tile = True, favourites_count = 10, name = u 'mc bacelar', url = None, created_at = datetime.datetime(2012, 11, 5, 18, 59, 10), contributors_enabled = False, time_zone = None, profile_sidebar_border_color = u 'FFFFFF', default_profile = False, following = False, listed_count = 0), _json = {
    u 'contributors': None,
    u 'truncated': False,
    u 'text': u 'VAI PORRA  #worldcup',
    u 'in_reply_to_status_id': None,
    u 'id': 481147532840824833,
    u 'favorite_count': 0,
    u 'source': u '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    u 'retweeted': False,
    u 'coordinates': None,
    u 'entities': {
        u 'user_mentions': [],
        u 'symbols': [],
        u 'trends': [],
        u 'hashtags': [{
            u 'indices': [11, 20],
            u 'text': u 'worldcup'
        }],
        u 'urls': []
    },
    u 'in_reply_to_screen_name': None,
    u 'id_str': u '481147532840824833',
    u 'retweet_count': 0,
    u 'in_reply_to_user_id': None,
    u 'favorited': False,
    u 'user': {
        u 'follow_request_sent': None,
        u 'profile_use_background_image': True,
        u 'default_profile_image': False,
        u 'id': 928197300,
        u 'verified': False,
        u 'profile_image_url_https': u 'https://pbs.twimg.com/profile_images/478566662136803330/En6dtdRp_normal.jpeg',
        u 'profile_sidebar_fill_color': u 'DDEEF6',
        u 'profile_text_color': u '333333',
        u 'followers_count': 205,
        u 'profile_sidebar_border_color': u 'FFFFFF',
        u 'id_str': u '928197300',
        u 'profile_background_color': u 'C0DEED',
        u 'listed_count': 0,
        u 'profile_background_image_url_https': u 'https://pbs.twimg.com/profile_background_images/479444187616518144/TbB97uZ7.jpeg',
        u 'utc_offset': None,
        u 'statuses_count': 584,
        u 'description': u 'Talking Winning',
        u 'friends_count': 915,
        u 'location': u 'swangg',
        u 'profile_link_color': u '0084B4',
        u 'profile_image_url': u 'http://pbs.twimg.com/profile_images/478566662136803330/En6dtdRp_normal.jpeg',
        u 'following': None,
        u 'geo_enabled': True,
        u 'profile_banner_url': u 'https://pbs.twimg.com/profile_banners/928197300/1403143442',
        u 'profile_background_image_url': u 'http://pbs.twimg.com/profile_background_images/479444187616518144/TbB97uZ7.jpeg',
        u 'name': u 'mc bacelar',
        u 'lang': u 'pt',
        u 'profile_background_tile': True,
        u 'favourites_count': 10,
        u 'screen_name': u 'bacelar_santos',
        u 'notifications': None,
        u 'url': None,
        u 'created_at': u 'Mon Nov 05 18:59:10 +0000 2012',
        u 'contributors_enabled': False,
        u 'time_zone': None,
        u 'protected': False,
        u 'default_profile': False,
        u 'is_translator': False
    },
    u 'geo': None,
    u 'in_reply_to_user_id_str': None,
    u 'possibly_sensitive': False,
    u 'lang': u 'en',
    u 'created_at': u 'Mon Jun 23 18:51:25 +0000 2014',
    u 'filter_level': u 'medium',
    u 'in_reply_to_status_id_str': None,
    u 'place': None
}, coordinates = None, entities = {
    u 'user_mentions': [],
    u 'symbols': [],
    u 'trends': [],
    u 'hashtags': [{
        u 'indices': [11, 20],
        u 'text': u 'worldcup'
    }],
    u 'urls': []
}, in_reply_to_screen_name = None, id_str = u '481147532840824833', retweet_count = 0, in_reply_to_user_id = None, favorited = False, source_url = u 'http://twitter.com', user = User(follow_request_sent = None, profile_use_background_image = True, _json = {
    u 'follow_request_sent': None,
    u 'profile_use_background_image': True,
    u 'default_profile_image': False,
    u 'id': 928197300,
    u 'verified': False,
    u 'profile_image_url_https': u 'https://pbs.twimg.com/profile_images/478566662136803330/En6dtdRp_normal.jpeg',
    u 'profile_sidebar_fill_color': u 'DDEEF6',
    u 'profile_text_color': u '333333',
    u 'followers_count': 205,
    u 'profile_sidebar_border_color': u 'FFFFFF',
    u 'id_str': u '928197300',
    u 'profile_background_color': u 'C0DEED',
    u 'listed_count': 0,
    u 'profile_background_image_url_https': u 'https://pbs.twimg.com/profile_background_images/479444187616518144/TbB97uZ7.jpeg',
    u 'utc_offset': None,
    u 'statuses_count': 584,
    u 'description': u 'Talking Winning',
    u 'friends_count': 915,
    u 'location': u 'swangg',
    u 'profile_link_color': u '0084B4',
    u 'profile_image_url': u 'http://pbs.twimg.com/profile_images/478566662136803330/En6dtdRp_normal.jpeg',
    u 'following': None,
    u 'geo_enabled': True,
    u 'profile_banner_url': u 'https://pbs.twimg.com/profile_banners/928197300/1403143442',
    u 'profile_background_image_url': u 'http://pbs.twimg.com/profile_background_images/479444187616518144/TbB97uZ7.jpeg',
    u 'name': u 'mc bacelar',
    u 'lang': u 'pt',
    u 'profile_background_tile': True,
    u 'favourites_count': 10,
    u 'screen_name': u 'bacelar_santos',
    u 'notifications': None,
    u 'url': None,
    u 'created_at': u 'Mon Nov 05 18:59:10 +0000 2012',
    u 'contributors_enabled': False,
    u 'time_zone': None,
    u 'protected': False,
    u 'default_profile': False,
    u 'is_translator': False
}, id = 928197300, _api = < tweepy.api.API object at 0x109078e90 > , verified = False, profile_image_url_https = u 'https://pbs.twimg.com/profile_images/478566662136803330/En6dtdRp_normal.jpeg', profile_sidebar_fill_color = u 'DDEEF6', is_translator = False, geo_enabled = True, profile_text_color = u '333333', followers_count = 205, protected = False, location = u 'swangg', default_profile_image = False, id_str = u '928197300', utc_offset = None, statuses_count = 584, description = u 'Talking Winning', friends_count = 915, profile_link_color = u '0084B4', profile_image_url = u 'http://pbs.twimg.com/profile_images/478566662136803330/En6dtdRp_normal.jpeg', notifications = None, profile_background_image_url_https = u 'https://pbs.twimg.com/profile_background_images/479444187616518144/TbB97uZ7.jpeg', profile_background_color = u 'C0DEED', profile_banner_url = u 'https://pbs.twimg.com/profile_banners/928197300/1403143442', profile_background_image_url = u 'http://pbs.twimg.com/profile_background_images/479444187616518144/TbB97uZ7.jpeg', screen_name = u 'bacelar_santos', lang = u 'pt', profile_background_tile = True, favourites_count = 10, name = u 'mc bacelar', url = None, created_at = datetime.datetime(2012, 11, 5, 18, 59, 10), contributors_enabled = False, time_zone = None, profile_sidebar_border_color = u 'FFFFFF', default_profile = False, following = False, listed_count = 0), geo = None, in_reply_to_user_id_str = None, possibly_sensitive = False, lang = u 'en', created_at = datetime.datetime(2014, 6, 23, 18, 51, 25), filter_level = u 'medium', in_reply_to_status_id_str = None, place = None, source = u 'Twitter Web Client', retweeted = False)